#include <Keypad.h>
#define LED 13

const uint8_t ROWS = 4;
const uint8_t COLS = 4;
char keys[ROWS][COLS] = {
  { '1', '2', '3', 'A' },
  { '4', '5', '6', 'B' },
  { '7', '8', '9', 'C' },
  { '*', '0', '#', 'D' }
};

uint8_t colPins[COLS] = { 5, 4, 3, 2 }; // Pins connected to C1, C2, C3, C4
uint8_t rowPins[ROWS] = { 9, 8, 7, 6 }; // Pins connected to R1, R2, R3, R4

Keypad keypad = Keypad( makeKeymap(keys), rowPins, colPins, ROWS, COLS );

void setup(){
  pinMode(LED, OUTPUT);
  Serial.begin(9600);
}
  
void loop(){
  char key = keypad.getKey();
  digitalWrite(LED, LOW);
  
  if (key){
    switch (key)
    {
      case '1':
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        break;
      case '2':
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
      break;
      case '3':
              digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
      break;
      case '4':
              digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
      break;
      case '5':
              digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
      break;
      case '6':
              digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
      break;
      case '7':
              digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
      break;
      case '8':
              digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
      break;
      case '9':
              digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
                digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
        digitalWrite(LED, HIGH); 
        delay(10000);
      break;
    }
  }
}
